# Generated by Django 4.0 on 2022-01-04 16:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_contanct_number_supplier_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fridgecontent',
            name='introduction_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='fridgecontent',
            name='quantity',
            field=models.FloatField(),
        ),
    ]
