# Generated by Django 4.0 on 2022-01-04 17:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_fridgecontent_expiration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fridgecontent',
            name='expiration_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='fridgecontent',
            name='introduction_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
