# Generated by Django 4.0 on 2022-01-04 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_fridgecontent_expiration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fridgecontent',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
