# Generated by Django 4.0 on 2022-01-04 21:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_fridgecontent_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fridgecontent',
            name='expiration_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='fridgecontent',
            name='introduction_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
