# Generated by Django 4.0 on 2022-01-05 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20220105_2020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='door',
            old_name='lock_status',
            new_name='door_locked',
        ),
    ]
