# Generated by Django 4.0 on 2022-01-09 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_fridgecontent_introduction_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fridgecontent',
            old_name='quantity',
            new_name='current_quantity',
        ),
        migrations.AddField(
            model_name='fridgecontent',
            name='default_quantity',
            field=models.FloatField(default=0),
        ),
    ]
