# Generated by Django 4.0 on 2022-01-09 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_quantity_fridgecontent_current_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fridgecontent',
            name='reordered',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
