# Generated by Django 4.0 on 2022-02-04 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_notification_creation_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.item')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliveryDriver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
                ('orderItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.orderitem')),
            ],
        ),
    ]
