# Generated by Django 4.0 on 2022-02-04 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_order_orderitem_order_orderitems'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='orderItems',
            new_name='order_items',
        ),
    ]
