# Generated by Django 4.0 on 2022-02-06 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_rename_orderitems_order_order_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='deliveryDriver',
            new_name='delivery_driver',
        ),
        migrations.AddField(
            model_name='order',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
    ]
