# Generated by Django 4.0 on 2022-02-06 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_rename_deliverydriver_order_delivery_driver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_driver',
            field=models.ForeignKey(limit_choices_to={'role': 'DD'}, on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
    ]
